downgrade to java 8
e.g. on Debian 8, Maven will install java 11, which is too high for verapdf rest api (when starting, one will get a  java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException since that had been moved)